name: 'Python SonarQube API Workflows'

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  - name: Python
    runs-on: ubantu-latest

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9' 
      
    - name: Run a python file
      run: python sonarqube_webapi.py